# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy all source code into the image
COPY . .

# Copy and install torch manually from local .whl file ( downloaded manually)
COPY torch-2.2.2+cpu-cp310-cp310-linux_x86_64.whl .

# Install dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir torch-2.2.2+cpu-cp310-cp310-linux_x86_64.whl && \
    pip install --no-cache-dir --timeout=100 --retries=10 -r requirements.txt

# Expose port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "rag_api:app", "--host", "0.0.0.0", "--port", "8000"]
